spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/luxoft
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  version: v1